/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as RjssRouteImport } from './routes/rjss'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MultiverseRouteImport } from './routes/multiverse'
import { Route as MindRouteImport } from './routes/mind'
import { Route as GoieRouteImport } from './routes/goie'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as IndexRouteImport } from './routes/index'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const RjssRoute = RjssRouteImport.update({
  id: '/rjss',
  path: '/rjss',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiverseRoute = MultiverseRouteImport.update({
  id: '/multiverse',
  path: '/multiverse',
  getParentRoute: () => rootRouteImport,
} as any)
const MindRoute = MindRouteImport.update({
  id: '/mind',
  path: '/mind',
  getParentRoute: () => rootRouteImport,
} as any)
const GoieRoute = GoieRouteImport.update({
  id: '/goie',
  path: '/goie',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/goie': typeof GoieRoute
  '/mind': typeof MindRoute
  '/multiverse': typeof MultiverseRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/rjss': typeof RjssRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/goie': typeof GoieRoute
  '/mind': typeof MindRoute
  '/multiverse': typeof MultiverseRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/rjss': typeof RjssRoute
  '/voice': typeof VoiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/courses': typeof CoursesRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/goie': typeof GoieRoute
  '/mind': typeof MindRoute
  '/multiverse': typeof MultiverseRoute
  '/news': typeof NewsRoute
  '/people': typeof PeopleRoute
  '/profile': typeof ProfileRoute
  '/rjss': typeof RjssRoute
  '/voice': typeof VoiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/goie'
    | '/mind'
    | '/multiverse'
    | '/news'
    | '/people'
    | '/profile'
    | '/rjss'
    | '/voice'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/goie'
    | '/mind'
    | '/multiverse'
    | '/news'
    | '/people'
    | '/profile'
    | '/rjss'
    | '/voice'
  id:
    | '__root__'
    | '/'
    | '/courses'
    | '/dashboard'
    | '/explore'
    | '/goie'
    | '/mind'
    | '/multiverse'
    | '/news'
    | '/people'
    | '/profile'
    | '/rjss'
    | '/voice'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoursesRoute: typeof CoursesRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  GoieRoute: typeof GoieRoute
  MindRoute: typeof MindRoute
  MultiverseRoute: typeof MultiverseRoute
  NewsRoute: typeof NewsRoute
  PeopleRoute: typeof PeopleRoute
  ProfileRoute: typeof ProfileRoute
  RjssRoute: typeof RjssRoute
  VoiceRoute: typeof VoiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rjss': {
      id: '/rjss'
      path: '/rjss'
      fullPath: '/rjss'
      preLoaderRoute: typeof RjssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multiverse': {
      id: '/multiverse'
      path: '/multiverse'
      fullPath: '/multiverse'
      preLoaderRoute: typeof MultiverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mind': {
      id: '/mind'
      path: '/mind'
      fullPath: '/mind'
      preLoaderRoute: typeof MindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goie': {
      id: '/goie'
      path: '/goie'
      fullPath: '/goie'
      preLoaderRoute: typeof GoieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoursesRoute: CoursesRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  GoieRoute: GoieRoute,
  MindRoute: MindRoute,
  MultiverseRoute: MultiverseRoute,
  NewsRoute: NewsRoute,
  PeopleRoute: PeopleRoute,
  ProfileRoute: ProfileRoute,
  RjssRoute: RjssRoute,
  VoiceRoute: VoiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
